version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=workout+5
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=AvitoTender
      - POSTGRES_CONN=postgres://postgres:workout+5@db:5432/AvitoTender?sslmode=disable
      - POSTGRES_JDBC_URL=jdbc:postgresql://db:5432/AvitoTender
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: AvitoTender
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: workout+5
    ports:
      - "5432:5432"